### ISSUE TITLE
Restructure directory

### ISSUE THREAD

**Issue by hmm34** [srcML/srcML#1105]
Some options discussed at the meeting today were:
- moving `cli/` to `test/client`
- moving the `test/unit` and `test/suite` directory to the location of the component it's testing
- moving the subdirectories of `src/` into the root level, with subdirectories for `src/`

Some alternatives:

```
srcML/
  libsrcml/
    test/
    src/
  srcml(client? cli?)/
    test/
    src/
  parser/
    test/
    src/
  ...
```

```
srcML/
  src/
    libsrcml/
    parser/
    ...
  test/
    libsrcml/
      unit/
      suite/
    parser/
      unit/
      suite/
    client/
      unit/
      suite/
  ...
```

```
srcML/
  libsrcml/
  parser/
  ...
  test/
    libsrcml/
      unit/
      suite/
    parser/
      unit/
      suite/
    ...
```

Personally I like the idea of separate directories for libsrcml, client, and parser at the root level because it seems more modular than putting them together under src/.

The folder structure is open for more discussion. Thoughts?

**Comment by mlcollard** [comment]
This is already complete
