### ISSUE TITLE
Antlr Migration

### ISSUE THREAD

**Issue by mjdecker** [srcML/srcML#135]
Currently, srcML uses antlr2.

antlr3 and antlr4 have been released.

antlr3 is supposed to have a C++ target for version 3.4, however, the current version 3.5.1 does not appear to support it.  Also, the files for version 3.4 (are kind of hard to find). (A C target does exist).

antlr4 is supposed to support a C++ target, however, the release has been delayed.

Should we bother migrating from 2->3 and just wait for 4 to go from 2->4?

**Comment by mlcollard** [comment]
Closing this as this would be a new initiative.
