### ISSUE TITLE
Position of <block_content> and similar elements

### ISSUE THREAD

**Issue by mlcollard** [srcML/srcML#1707]
The position attributes for elements that contain trailing whitespace is not clear. This comes from #1697. 

The best example is `<block_content>`

Take this starting code:

```C++
{
return;
}
```

Here is the srcML (without position):

```XML
<block>{<block_content>
<return>return;</return> 
</block_content>}</block>
```

Note that the `<block_content>` ends inside of the '}' of the `<block>`.

Here it is source marked with line, columns, and returns:
```console
  123456789
1 {⏎
2 return;⏎
3 }⏎
```

There are two possibilities for the end position of `<block_content>`: 

In this one (Option B below), the position is not really valid. "3:0" is line 3, column 0, but columns start at 1. Note that the end position of `<block_content>`  must be (in some sense) 1 column "less" than the column of `<block>`:

```XML
<block pos:start="1:1" pos:end="3:1">{<block_content pos:start="1:2" pos:end="3:0">
<return pos:start="2:1" pos:end="2:7">return;</return> 
</block_content>}</block>
```

In this one (Option A below), the position is the end (the newline) of the previous line. Since there are 7 characters on the line with the `return;`, it is column 8:

```XML
<block pos:start="1:1" pos:end="3:1">{<block_content pos:start="1:2" pos:end="2:8">
<return pos:start="2:1" pos:end="2:7">return;</return> 
</block_content>}</block>
```

In this case a space is added to right before the '}', and this is fine:

```XML
<block pos:start="1:1" pos:end="3:2">{<block_content pos:start="1:2" pos:end="3:1">
<return pos:start="2:1" pos:end="2:7">return;</return>
 </block_content>}</block>
```

So the rule is whenever an element ends at the start of a line (i.e., before any characters), the end position is either:

A: The position of the newline on the previous line
B: Has a column of 0

Which one makes more sense?

**Comment by mlcollard** [comment]
Other examples of these elements which may contain trailing whitespace:

* Access specifiers, e.g., `<private>`:
  ```XML
  1 <class pos:start="1:1" pos:end="3:2">class <name pos:start="1:7" pos:end="1:7">A</name> 
  2 <block pos:start="2:1" pos:end="3:1">{<private type="default" pos:start="2:2" pos:end="2:2">
  3 </private>}</block>;</class>
  ```

* The then part of a ternary (`<then>`):
  ```XML
  1 <expr pos:start="1:1" pos:end="2:1"><ternary pos:start="1:1" pos:end="2:1"><condition pos:start="1:1" pos:end="1:3"><expr pos:start="1:1" pos:end="1:1"><name pos:start="1:1" pos:end="1:1">A</name></expr> ?</condition><then pos:start="1:4" pos:end="1:6"> <expr pos:start="1:5" pos:end="1:5"><literal type="number" pos:start="1:5" pos:end="1:5">1</literal></expr> 
  2 </then><else pos:start="2:1" pos:end="2:1">:</else></ternary></expr>
  ```

**Comment by e-shreve-ti** [comment]
Just to clarify option A, the end pos for block_content would be 3:1 in the following example:
```
  123456789
1 {⏎
2 return;⏎
3 ⏎
4 }⏎
```
My 2 cents is that option A is best. It avoids dealing with col=0 as a special case in code that parses the srcml.

**Comment by mlcollard** [comment]
The answer for option A is:

```
  123456789
1 {⏎
2 ⏎
3 }⏎
```

is:

```XML
<block pos:start="1:1" pos:end="3:1">{<block_content pos:start="1:2" pos:end="2:1">

</block_content>}</block>
```

**Comment by mlcollard** [comment]
Option A

**Comment by e-shreve** [comment]
I'm also finding that the starting position for block_content to be unclear/inconsistent. Not sure if it deserves its own github issue or should be a part of this one. Here is an example:
```
{
#include <stdint.h>
uint8_t myGlobal;
#define MYVAL 0
}
```
This results in srcml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<unit xmlns="http://www.srcML.org/srcML/src" xmlns:cpp="http://www.srcML.org/srcML/cpp" xmlns:pos="http://www.srcML.org/srcML/position" revision="1.0.0" language="C" filename="./blockcontent.c" pos:tabs="8"><block pos:start="1:1" pos:end="5:1">{<block_content pos:start="3:1" pos:end="5:0">
<cpp:include pos:start="2:1" pos:end="2:19">#<cpp:directive pos:start="2:2" pos:end="2:8">include</cpp:directive> <cpp:file pos:start="2:10" pos:end="2:19">&lt;stdint.h&gt;</cpp:file></cpp:include>
<decl_stmt pos:start="3:1" pos:end="5:0"><decl pos:start="3:1" pos:end="3:16"><type pos:start="3:1" pos:end="3:7"><name pos:start="3:1" pos:end="3:7">uint8_t</name></type> <name pos:start="3:9" pos:end="3:16">myGlobal</name></decl>;</decl_stmt>
<cpp:define pos:start="4:1" pos:end="4:15">#<cpp:directive pos:start="4:2" pos:end="4:7">define</cpp:directive> <cpp:macro pos:start="4:9" pos:end="4:13"><name pos:start="4:9" pos:end="4:13">MYVAL</name></cpp:macro> <cpp:value pos:start="4:15" pos:end="4:15">0</cpp:value></cpp:define>
</block_content>}</block></unit>

```

The example is simplified, but it occurs in the wild often in C header files when they have an "extern C" block.

The starting position for the block_content is listed as the first C language line. It skips over the CPP include. But the block_content tag does have the CPP include as a child tag (as well as the define tag) so the child tags of a block can be mixed language tags. Also, the define directive comes after the starting position so we can have mixed content between the starting and end positions.

Why not have the block_content starting position be the location of the opening block_content tag itself? If a user wants only the children of the block_content tag that match the language then they can use XPATH to exclude the CPP tags. It is also easy for users to strip leading and trailing whitespace of the text within block_content, so I see no need for the starting position attribute to 'jump' to the first non-whitespace character.

Of course, fixing this might mean that block_content's starting and ending position are always just after/before the start/end of a block tag's position. Which causes me to wonder if the block_content tag is needed at all?

**Comment by mlcollard** [comment]
We had this issue come up later. Went with a column of 0. That way the `<block_content>` is on the same line as the `<block>` and in one column less.
