### ISSUE TITLE
antlr version?

### ISSUE THREAD

**Issue by csiefer2** [srcML/srcML#1711]
What version of antlr do you need to build srcML from source?

**Comment by e-shreve** [comment]
It is antlr2. I've built it with 2.7.7 which is the latest. I found the docker files referenced at https://github.com/srcML/srcML/blob/d58678efd31b72fe642b251ea613cd54ebfe1bb0/BUILD.md#linux to be helpful.

**Comment by csiefer2** [comment]
As a note, srcML doesn't link against the Redhat Enterprise Linux 7.8 version of libantlr (which is 2.7.7-30).

Did you build antlr 2..7.7 from source?  If so, what compiler did you use?  Antlr doesn't compile with  gcc 5.3.0.  It's missing a bunch of header includes (e.g. cstdio) all over the place.

**Comment by e-shreve** [comment]
I built in an Ubuntu 16.04 VM. Ubuntu has a libantlr-dev package as well as an antlr package, both are dependencies for building srcml in ubuntu from what I recall.
