### ISSUE TITLE
Can srcML be used to extract control-flow and basic data-flow graphs?

### ISSUE THREAD

**Issue by nashid** [srcML/srcML#1776]
I came across srcML during MSR and this library looks great! 

I need to extract control-flow and basic data-flow graphs i.e. def-use for intraprocedural analysis with Java. My intention is to feed the enclosing function body of the java source code.

I am wondering whether srcML is a good fit to extract control-flow and data-flow edges? Is there a working example in this regard?

**Comment by jmaletic** [comment]
Talked via discord.
