### ISSUE TITLE
Libarchive versions for macOS

### ISSUE THREAD

**Issue by mlcollard** [srcML/srcML#1885]
On macOS, the built-in libarchive is used. To build against it, archive.h and archive_entry.h must be downloaded. This is done via a URL and `FetchContent`. Here is the current table

| Name | OS | Libarchive | |
|:-|:-:|-:|-|
| macOS Ventura 13 | 22 |  | 3.5.3  |
| macOS Monterey 12 | 21 | 103 | 3.5.1 |
| macOS Big Sur 11 | 20 | 83.100.2 | 3.3.2 |
| macOS Catalina 10.15 | 19 | 72.140.1 | 3.3.2 |

**Comment by mlcollard** [comment]
Pushed directly to develop. Need to work on these a bit, but they work for now.

**Comment by dmgerman** [comment]
the src/CMakeLists.txt would benefit from using $HOMEBREW_PREFIX. In new non-intel macs, the path for homebrew has changed to /opt/homebrew

This would affect finding libarchive and antlr

also, it looks like the name LibArchive_INCLUDE_DIRS should be LibArchive_INCLUDE_DIR

With these changes, I was able to get cmake to run on an M1.

But I am getting a compilation error (
/Users/dmg/git.w/srcML/src/client/src_input_file.cpp:41:28: error: no viable overloaded '='
)  around 68% of the build process. I don't think these are related.

**Comment by mlcollard** [comment]
We've converted to a better way to get libarchive. All of the fixes for the M1 are in the develop branch.
