### ISSUE TITLE
Java Record Classes

### ISSUE THREAD

**Issue by mjdecker** [srcML/srcML#2055]
A basic record class.
```Java
record Rectangle(double length, double width) { }
```

Data members given in `()`, and an `public` interface is auto-generated.  The full expansion is this:
```Java
public final class Rectangle {
    private final double length;
    private final double width;

    public Rectangle(double length, double width) {
        this.length = length;
        this.width = width;
    }

    double length() { return this.length; }
    double width()  { return this.width; }

    // Implementation of equals() and hashCode(), which specify
    // that two record objects are equal if they
    // are of the same type and contain equal field values.
    public boolean equals...
    public int hashCode...

    // An implementation of toString() that returns a string
    // representation of all the record class's fields,
    // including their names.
    public String toString() {...}
}
```

Note the body of the class can still have additional components declared.

```Java
record Rectangle(double length, double width) {
    public Rectangle(double length, double width) {
        if (length <= 0 || width <= 0) {
            throw new java.lang.IllegalArgumentException(
                String.format("Invalid dimensions: %f, %f", length, width));
        }
        this.length = length;
        this.width = width;
    }
}
```

Suggestion is to markup as class with type record.  For data members, I don't think parameter_list is essentially a bad idea. Especially, if we want to avoid any new tags.  However, we could also use another tag. Since these  are similar to C# properties maybe property_list/property

parameter_list
```xml
<class type="record">record <name>Rectangle</name><parameter_list>(<parameter><decl><type><name>double</name></type> <name>length</name></decl></parameter>, <parameter><decl><type><name>double</name></type> <name>width</name></decl></parameter>)</parameter_list> <block>{}</block></class>
```

property_list
```xml
<class type="record">record <name>Rectangle</name><property_list>(<property><decl><type><name>double</name></type> <name>length</name></decl></property>, <property><decl><type><name>double</name></type> <name>width</name></decl></property>)</property_list> <block>{}</block></class>
```

Note: record seems to be contextual

**Comment by aalramadan** [comment]
Just adding this here since there was an issue previously on this:
https://github.com/srcML/srcML/issues/1989

**Comment by mjdecker** [comment]
Yeah. I saw it afterwards. It lumps in C# and Java though. C# seems to be the primary focus? It is probably good to separate the two.

**Comment by mjdecker** [comment]
Created a branch issue2055.

It will contextually parse a record.  It does not put an attribute on class and parses the `()` part as a parameter list for now (easiest to do to get working for now).

**Comment by aalramadan** [comment]
Perfect, I will remove the Java stuff as you suggested and focus on C# alone.

**Comment by mjdecker** [comment]
Add without the attribute on the class tag.  When tag-set change, will add attribute.

**Comment by mjdecker** [comment]
Merged into develop.
